version: '3'
services:
  db:
    container_name: mariadb
    image: mariadb:10.8.2-rc
    restart: always
    environment:
      MARIADB_DATABASE: frame_2022_0005
      MARIADB_USER: atech
      MARIADB_PASSWORD: Dpdlxpzm1221!@
      MARIADB_ROOT_PASSWORD: Dpdlxpzm1221!@
    ports:
      - 3306:3306
    volumes:
      - ./vol_db/data:/var/lib/mysql
      - ./vol_db/conf.d:/etc/mysql/conf.d
    networks:
        main:
            aliases:
                - db

  frontend:
    build: .
    # image: nginx:latest
    container_name: frontend
    ports:
      - "3000:80"
      - "443:443"
    volumes:
      - ./nginx_conf/nginx.conf:/etc/nginx/nginx.conf
      # - ./build:/home/build
    restart: "unless-stopped" # 내부에서 에러로 인해 container가 죽을 경우 restart
    networks:
        main:
            aliases:
                - frontend

  backend:
    container_name: spring-app
    image: openjdk:8-jdk
    ports:
        - "8080:8080"
    volumes:
        - ./backend:/app
    working_dir: /app
    command: ["./gradlew", "bootrun"]
    depends_on:
        - db
    restart: always
    networks:
        main:
            aliases:
                - backend
networks:
    main:
        name: main-net
