spring:
  application:
    name: rest-api
  datasource:
    url: jdbc:mysql://172.30.1.108:3306/test_jjlee?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: atech
    password: dpdlxpzm1221!@
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  jwt:
    secret: testtt123443211234

  profiles:
    default: dev

  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

server:
  servlet:
    session:
      timeout: 1h
      cookie:
        max-age: 1h
